name: maven build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: tomcat-deploy
      run: curl -v -u tomcat:s3cret -T /home/runner/work/githubactions_javamaven/githubactions_javamaven/target/spring3-mvc-maven-xml-hello-world-3.0-SNAPSHOT.war 'http://54.90.255.248:8090//manager/text/deploy?path=/myweb_dev_action&update=true'
    
    


    
