name: snyk-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: snyk/actions/setup@master
    - name: snyk-test
    - run: snyk test
    env:
      SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
    
